language: r
sudo: required
cache: packages

r_packages:
 - devtools
 - DT

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('UKGov-Data-Science/RAP-demo')"
  - Rscript -e "if (!require('DT')) install.packages('DT')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
